version: "3.8"
services:
  keg-components:
    privileged: true
    build:
      context: ${KEG_CONTEXT_PATH}
      dockerfile: ${KEG_DOCKER_FILE}
      args:
        - EXPO_DEVTOOLS_LISTEN_ADDRESS: ${EXPO_DEVTOOLS_LISTEN_ADDRESS:-0.0.0.0}
        - KEG_DOCKER_IP: ${KEG_DOCKER_IP:-0.0.0.0}
        - DOC_APP_PATH: ${DOC_APP_PATH:-/keg/components}
        - BASE_IMAGE_FROM
        - KEG_NODE_VERSION
    environment:
      - CHOKIDAR_USEPOLLING
      - DOC_APP_PATH
      - DOC_CLI_PATH
      - DOC_COMPONENTS_PATH
      - DOC_RETHEME_PATH
      - DOC_JSUTILS_PATH
      - KEG_EXEC_CMD
      - KEG_DOCKER_EXEC
      - KEG_NM_INSTALL
      - NODE_ENV
