version: "3.8"
services:
  keg-base:
    image: ${IMAGE}
    build:
      context: ${KEG_CONTEXT_PATH}
      dockerfile: ${KEG_DOCKER_FILE}
      args:
        - EXPO_CLI_VERSION
        - GIT_HUB_URL
        - GIT_HUB_BRANCH
        - KEG_COPY_LOCAL
        - KEG_DOCKER_IP
        - KEG_NODE_VERSION
    container_name: ${CONTAINER_NAME}
