
name: keg-pr-changes
on: pull_request

jobs:
  tests:
    name: 'Generate changed files list'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Get Changed Files"
        id: get-changed-files
        run: bash scripts/ci/getChangedFiles.sh
      - name: "Get Changed Repos"
        id: get-changed-repos
        run: bash scripts/ci/getChangedRepos.sh
      - name: "Generate PR Changes"
        id: generate-pr-changes
        run: bash scripts/ci/generatePRChanges.sh
      # - name: "Add Comment To PR"
      #   uses: peter-evans/create-or-update-comment@v1
      - name: Find Comment
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: '### Changed Files'

      - name: Create comment
        if: ${{ steps.fc.outputs.comment-id == 0 }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ steps.generate-pr-changes.outputs.pr-changes }}

      - name: Update comment
        if: ${{ steps.fc.outputs.comment-id != 0 }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          body: ${{ steps.generate-pr-changes.outputs.pr-changes }}

